Import("env")
import gzip
import os

pages = [
    ("index.html",         "INDEX_HTML"),
    ("wifi_config.html",   "WIFI_CONFIG_HTML"),
    ("notifications.html", "NOTIFICATIONS_HTML"),
    ("ota.html",           "OTA_HTML"),
    ("settings.html",      "SETTINGS_HTML"),
]

html_dir = os.path.join(env["PROJECT_DIR"], "src", "html")
out_path = os.path.join(env["PROJECT_DIR"], "src", "compressed_pages.h")

with open(out_path, "w") as out:
    out.write("// Auto-generated by scripts/compress_html.py — do not edit\n")
    out.write("#pragma once\n")
    out.write("#include <pgmspace.h>\n\n")

    for filename, varname in pages:
        src = os.path.join(html_dir, filename)
        with open(src, "rb") as f:
            raw = f.read()
        compressed = gzip.compress(raw, compresslevel=9)
        ratio = 100 * len(compressed) // len(raw)
        print(f"  {filename}: {len(raw)}B -> {len(compressed)}B ({ratio}%)")

        hex_bytes = ", ".join(f"0x{b:02x}" for b in compressed)
        out.write(f"const uint8_t {varname}_GZ[] PROGMEM = {{{hex_bytes}}};\n")
        out.write(f"const size_t {varname}_GZ_LEN = {len(compressed)};\n\n")
