Import("env")
import gzip
import os

project_dir = env["PROJECT_DIR"]
dev_ui_dir  = os.path.join(project_dir, "dev-ui")
src_html_dir = os.path.join(project_dir, "src", "html")

# (source_dir, filename, varname)
pages = [
    (dev_ui_dir,  "index.html",         "INDEX_HTML"),
    (dev_ui_dir,  "wifi-config.html",   "WIFI_CONFIG_HTML"),
    (dev_ui_dir,  "notifications.html", "NOTIFICATIONS_HTML"),
    (dev_ui_dir,  "settings.html",      "SETTINGS_HTML"),
    (dev_ui_dir,  "debug.html",         "DEBUG_HTML"),
    (src_html_dir, "ota.html",          "OTA_HTML"),
]

out_path = os.path.join(project_dir, "src", "compressed_pages.h")

with open(out_path, "w") as out:
    out.write("// Auto-generated by scripts/compress_html.py — do not edit\n")
    out.write("#pragma once\n")
    out.write("#include <pgmspace.h>\n\n")

    for src_dir, filename, varname in pages:
        src = os.path.join(src_dir, filename)
        with open(src, "rb") as f:
            raw = f.read()
        compressed = gzip.compress(raw, compresslevel=9)
        ratio = 100 * len(compressed) // len(raw)
        print(f"  {filename}: {len(raw)}B -> {len(compressed)}B ({ratio}%)")

        hex_bytes = ", ".join(f"0x{b:02x}" for b in compressed)
        out.write(f"const uint8_t {varname}_GZ[] PROGMEM = {{{hex_bytes}}};\n")
        out.write(f"const size_t {varname}_GZ_LEN = {len(compressed)};\n\n")
